"""ChSeparating Posts table user id attribute in two, requester user id and assigned user id

Revision ID: 116a35f62994
Revises: 1fce0dff5d1b
Create Date: 2026-05-22 16:25:18.992256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116a35f62994'
down_revision: Union[str, Sequence[str], None] = '1fce0dff5d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_posts')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_requester_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_assigned_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_posts_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_posts_user_requester_id_users'), 'users', ['user_requester_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_posts_user_assigned_id_users'), 'users', ['user_assigned_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_posts_user_assigned_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_posts_user_requester_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_posts_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('user_assigned_id')
        batch_op.drop_column('user_requester_id')

    op.create_table('_alembic_tmp_posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('machine_id', sa.INTEGER(), nullable=False),
    sa.Column('interruption_id', sa.INTEGER(), nullable=True),
    sa.Column('substation_id', sa.INTEGER(), nullable=True),
    sa.Column('device_id', sa.INTEGER(), nullable=True),
    sa.Column('error_cause_id', sa.INTEGER(), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('user_requester_id', sa.INTEGER(), nullable=False),
    sa.Column('user_assigned_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_posts_device_id_devices')),
    sa.ForeignKeyConstraint(['error_cause_id'], ['error_causes.id'], name=op.f('fk_posts_error_cause_id_error_causes')),
    sa.ForeignKeyConstraint(['interruption_id'], ['interruption_types.id'], name=op.f('fk_posts_interruption_id_interruption_types')),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_posts_machine_id_machines')),
    sa.ForeignKeyConstraint(['substation_id'], ['substations.id'], name=op.f('fk_posts_substation_id_substations')),
    sa.ForeignKeyConstraint(['user_assigned_id'], ['users.id'], name=op.f('fk_posts_user_assigned_id_users')),
    sa.ForeignKeyConstraint(['user_requester_id'], ['users.id'], name=op.f('fk_posts_user_requester_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    # ### end Alembic commands ###
