"""Changing Users attribute employee_id to employee_number, also it is changed from interger to string type, due employee card barcode contains a letter A at the end of the employee number

Revision ID: 1fce0dff5d1b
Revises: 
Create Date: 2026-05-22 12:04:39.787752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fce0dff5d1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_causes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_causes'))
    )
    op.create_table('interruption_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interruption_types'))
    )
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machines')),
    sa.UniqueConstraint('name', name=op.f('uq_machines_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.String(length=16), nullable=False),
    sa.Column('first_name', sa.String(length=16), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_technician', sa.Boolean(), nullable=True),
    sa.Column('is_operator', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('employee_number', name=op.f('uq_users_employee_number'))
    )
    op.create_table('substations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_substations_machine_id_machines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_substations')),
    sa.UniqueConstraint('name', 'machine_id', name='uq_substation_per_machine')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('substation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['substation_id'], ['substations.id'], name=op.f('fk_devices_substation_id_substations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('name', 'substation_id', name='uq_device_per_substation')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('interruption_id', sa.Integer(), nullable=True),
    sa.Column('substation_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('error_cause_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_posts_device_id_devices')),
    sa.ForeignKeyConstraint(['error_cause_id'], ['error_causes.id'], name=op.f('fk_posts_error_cause_id_error_causes')),
    sa.ForeignKeyConstraint(['interruption_id'], ['interruption_types.id'], name=op.f('fk_posts_interruption_id_interruption_types')),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_posts_machine_id_machines')),
    sa.ForeignKeyConstraint(['substation_id'], ['substations.id'], name=op.f('fk_posts_substation_id_substations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('devices')
    op.drop_table('substations')
    op.drop_table('users')
    op.drop_table('machines')
    op.drop_table('interruption_types')
    op.drop_table('error_causes')
    # ### end Alembic commands ###
